#include "Device_Init.h"
#include "work.h"
#include "gpioctl.h"
#include "system.h"

void gpio_init(void)
{
	// 	SYS_SET_IOCFG(IOP04CFG,SYS_IOCFG_P04_GPIO);			/*LED2*/	
  	// GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_4,GPIO_MODE_OUTPUT);

	// 	SYS_SET_IOCFG(IOP14CFG,SYS_IOCFG_P14_GPIO);			/*LED-PR*/	
  	// GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_4,GPIO_MODE_OUTPUT);
	
	// 	SYS_SET_IOCFG(IOP15CFG,SYS_IOCFG_P15_GPIO);			/*KEY*/	
  	// GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_5,GPIO_MODE_INPUT_WITH_PULL_UP);

	// 	SYS_SET_IOCFG(IOP01CFG,SYS_IOCFG_P01_GPIO);			/*LED3*/	
  	// GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_1,GPIO_MODE_OUTPUT);
	
	// 	SYS_SET_IOCFG(IOP00CFG,SYS_IOCFG_P00_GPIO);			/*LED1*/	
  	// GPIO_CONFIG_IO_MODE(GPIO0,GPIO_PIN_0,GPIO_MODE_OUTPUT);

	//   	SYS_SET_IOCFG(IOP30CFG,SYS_IOCFG_P30_GPIO);			/*pwr_ctrl*/	
  	// GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_0,GPIO_MODE_OUTPUT);

	// SYS_SET_IOCFG(IOP12CFG,SYS_IOCFG_P12_GPIO);			/*motor_ctrl*/
  	// GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_2,GPIO_MODE_OUTPUT);
	
	// SYS_SET_IOCFG(IOP22CFG,SYS_IOCFG_P22_GPIO);			/*motor1_ctrl*/
  	// GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_2,GPIO_MODE_OUTPUT);

	SYS_SET_IOCFG(IOP32CFG,SYS_IOCFG_P32_GPIO);			/*充电中*/	
  	GPIO_CONFIG_IO_MODE(GPIO3,GPIO_PIN_2,GPIO_MODE_OUTPUT);

	SYS_SET_IOCFG(IOP44CFG,SYS_IOCFG_P44_GPIO);			/*充电完成*/	
  	GPIO_CONFIG_IO_MODE(GPIO4,GPIO_PIN_4,GPIO_MODE_OUTPUT);

	SYS_SET_IOCFG(IOP26CFG,SYS_IOCFG_P26_GPIO);			/*LED2*/	
  	GPIO_CONFIG_IO_MODE(GPIO2,GPIO_PIN_6,GPIO_MODE_OUTPUT);

        // GPIO_RESET_PIN(GPIO0,GPIO_PIN_0_MSK);
		// GPIO_RESET_PIN(GPIO0,GPIO_PIN_1_MSK);
		// GPIO_RESET_PIN(GPIO0,GPIO_PIN_4_MSK);
		// GPIO_RESET_PIN(GPIO1,GPIO_PIN_4_MSK);
		// GPIO_RESET_PIN(GPIO1,GPIO_PIN_2_MSK);
		// GPIO_RESET_PIN(GPIO2,GPIO_PIN_2_MSK);
		// GPIO_RESET_PIN(GPIO3,GPIO_PIN_0_MSK);
		GPIO_SET_PIN(GPIO2,GPIO_PIN_6_MSK);
	
}

void GPIO_Interrupt(unsigned char status)
{
	 if(status==1)
	 {
		/*
		(1)设置P12为上拉输入模式
		*/
		SYS_SET_IOCFG(IOP10CFG,SYS_IOCFG_P10_GPIO);			/*设置P12为GPIO模式*/	
		GPIO_CONFIG_IO_MODE(GPIO1,GPIO_PIN_0,GPIO_MODE_INPUT_WITH_PULL_UP);		
//		/*
//		(2)设置P12中断为下降沿中断模式
//		*/	
		GPIO_EnableInt(GPIO1,GPIO_PIN_0_MSK,GPIO_INT_EDGE_FALLING);
//		/*
//		(3)设置P12 IO口输入滤波		
//		*/		
		GPIO_EnableFilter(GPIO1,GPIO_PIN_0_MSK,GPIO_FILCLK_DIV_10);
//		/*
//		(4)设置GPIO1中断
//		*/
		GPIO_ClearIntFlag(GPIO1,GPIO_PIN_0);	/*清除P12中断标志位*/
		NVIC_EnableIRQ(GPIO1_IRQn);				/*开启GPIO1中断*/
		/*
		(5)设置GPIO1中断优先级
		*/	
		NVIC_SetPriority(GPIO1_IRQn,1);			/* 0~3, 0最高, 3最低*/
	 }
	 else if (status==0) 
	 {
	 	GPIO_DisableInt(GPIO1,GPIO_PIN_0_MSK);
	 	GPIO_DisableFilter(GPIO1,GPIO_PIN_0_MSK);
	 	NVIC_DisableIRQ(GPIO1_IRQn);				/*开启GPIO1中断*/
	 }
				
}

